services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: cinema-php
        ports:
            - "5173:5173"
        networks:
            - cinema_network
        volumes:
            - .:/application

    webserver:
        image: nginx:1.26.3-alpine
        container_name: cinema-nginx
        working_dir: /application
        networks:
            - cinema_network
        ports:
            - '80:80'
        volumes:
            - .:/application
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: cinema-db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - cinema_network
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - ./volumes/cinema-data:/var/lib/mysql

networks:
    cinema_network:
        driver: bridge

volumes:
    cinema-data:

